# -*- coding: utf-8 -*-
"""Nội dung báo cáo RLVD — phần 2: Chương 4–7 + Tài liệu tham khảo."""

ASSETS = "/home/uvhnael/projects/Red-Light-Violation-Detection/docs/report-assets"
SHOTS = ASSETS + "/shots"

BLOCKS_2 = [
    # ================= CHƯƠNG 4 =================
    {"type": "heading", "text": "CHƯƠNG 4. THIẾT KẾ HỆ THỐNG", "level": 1},

    {"type": "heading", "text": "4.1. System Architecture (Kiến trúc hệ thống)", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "Hệ thống được thiết kế theo mô hình ba tầng Edge — Central — Web, tách bạch trách nhiệm từng tầng (Hình 4.1): node biên chịu toàn bộ xử lý thị giác máy tính tại camera; máy chủ trung tâm sở hữu dữ liệu và nghiệp vụ; dashboard web là tầng trình bày thuần tuý, mọi truy cập dữ liệu đều qua trung tâm."},
    {"type": "image", "path": ASSETS + "/vn/architecture.png", "width_mm": 160},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.1. Kiến trúc tổng thể ba tầng Edge — Central — Web"},
    {"type": "paragraph", "style": "Body", "text": "Các quyết định kiến trúc chính:"},
    {"type": "bullet_list", "items": [
        "Tính toán đẩy xuống biên: detect + track + nhận diện đèn + OCR chạy ngay tại node cạnh camera, chỉ hồ sơ vi phạm (JSON + ảnh JPEG nén) mới truyền lên trung tâm — tiết kiệm băng thông và giúp node độc lập với chất lượng liên kết mạng.",
        "Đường truyền bền vững một chiều edge → central: hồ sơ ghi trước vào outbox SQLite (durable) rồi mới đẩy batch; khi trung tâm hoặc mạng lỗi, hồ sơ chờ và tự đẩy lại khi phục hồi, chống trùng lặp theo event_id (idempotent).",
        "Đường điều khiển hai chiều web → central → edge: mọi thao tác hiệu chuẩn từ dashboard đều qua EdgeProxyService của trung tâm (giải quyết địa chỉ node từ đăng ký, kèm token quản trị), web không kết nối thẳng xuống edge.",
        "Tách lưu trữ metadata (PostgreSQL) và media (MinIO — S3 compatible): bảng vi phạm nhẹ, ảnh bằng chứng lưu object storage, truy cập qua presigned URL/stream blob.",
        "Dashboard không chứa logic dữ liệu: Next.js rewrite /api/* về trung tâm, /edge-api/* về edge; web không import thư viện database hay AI.",
        "Triển khai Docker Compose toàn bộ 5 service (postgres, minio, central-server, web-dashboard, edge-pipeline) với healthcheck và phụ thuộc khởi động; một lệnh start.sh dựng cả stack.",
    ]},
    {"type": "paragraph", "style": "Body", "text": "Bảng phân bổ cổng khi triển khai đầy đủ: web-dashboard :3000, central-server :8002 (nội bộ :8000), edge-pipeline :8082 (nội bộ :8080), PostgreSQL :5432, MinIO :9010 (S3) và :9011 (console). Sơ đồ thành phần (Hình 4.2) và sơ đồ triển khai Docker (Hình 4.3) mô tả chi tiết cách các thành phần giao tiếp và đóng gói."},
    {"type": "image", "path": ASSETS + "/vn/component.png", "width_mm": 155},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.2. Sơ đồ thành phần (component diagram) tổng thể"},
    {"type": "image", "path": ASSETS + "/vn/deployment.png", "width_mm": 155},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.3. Sơ đồ triển khai Docker Compose (5 service trên mạng rlvd-net)"},

    {"type": "heading", "text": "4.2. Class Diagram", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "Tầng node biên được thiết kế hướng thành phần với lớp điều phối RedLightViolationPipeline tổng hợp các thành phần phát hiện, theo dõi, phân loại đèn, logic vi phạm và outbox (Hình 4.4). Điểm thiết kế đáng chú ý: ViolationDetector đọc lại tripwire đang hoạt động (get_active_tripwire) mỗi frame nên việc hiệu chuẩn từ xa áp dụng ngay mà không cần tái tạo đối tượng; PlateAssociator cache kết quả OCR theo track theo nguyên tắc “đọc đúng một lần” (chỉ nhận khi confidence ≥ 0,80 và độ dài cấu trúc hợp lệ). Sơ đồ cũng thể hiện lớp trung tâm (Controller — Service — Entity) và các component web chính để thấy toàn cảnh liên kết."},
    {"type": "image", "path": ASSETS + "/vn/class-diagram.png", "width_mm": 160},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.4. Class diagram — pipeline node biên, lớp trung tâm và component web"},
    {"type": "paragraph", "style": "Body", "text": "Về hành vi động, máy trạng thái quan trọng nhất của pipeline là vòng ổn định tín hiệu đèn (Hình 4.5): bộ phân loại chỉ “khóa” một màu khi quan sát liên tiếp đủ số frame (khóa đầu 3 frame, chuyển trạng thái 7 frame — cơ chế hysteresis chống nhấp nháy), và chỉ trạng thái ĐỎ ổn định mới mở nhánh xét vi phạm."},
    {"type": "image", "path": ASSETS + "/vn/state-light.png", "width_mm": 150},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.5. State diagram — trạng thái đèn tín hiệu có ổn định (debounce + hysteresis)"},

    {"type": "heading", "text": "4.3. ERD (Entity Relationship Diagram)", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "Mô hình dữ liệu nghiệp vụ của trung tâm gồm hai thực thể chính: edge_nodes (đăng ký node) và violations (hồ sơ vi phạm), quan hệ 1 — n: một node ghi nhận nhiều vi phạm (Hình 4.6). event_id là khoá nghiệp vụ duy nhất dùng chống trùng lặp khi đẩy batch."},
    {"type": "image", "path": ASSETS + "/vn/erd.png", "width_mm": 155},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.6. ERD — thực thể edge_nodes và violations"},

    {"type": "heading", "text": "4.4. Database Design (Thiết kế CSDL)", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "CSDL PostgreSQL rlvd_central gồm hai bảng chính, được sinh và quản lý bởi JPA (ddl-auto: update), múi giờ lưu trữ Asia/Ho_Chi_Minh."},
    {"type": "table", "header": ["Trường", "Kiểu", "Ràng buộc", "Ý nghĩa"], "rows": [
        ["id", "BIGSERIAL", "PK", "Khoá chính tự sinh"],
        ["event_id", "VARCHAR", "UNIQUE, NOT NULL", "Mã sự kiện do edge sinh (rlv-{run_id}-{frame}-{track}), chống trùng batch"],
        ["node_id", "VARCHAR(64)", "NOT NULL", "Mã node biên ghi nhận vi phạm"],
        ["track_id / frame_index", "INT", "—", "Định danh track phương tiện và frame phát sinh"],
        ["timestamp_ms", "DOUBLE", "—", "Thời điểm vi phạm theo luồng video (ms)"],
        ["crossing_point_x/y", "DOUBLE", "—", "Toạ độ điểm cắt vạch (tâm bbox)"],
        ["previous_point_x/y", "DOUBLE", "—", "Toạ độ điểm phía trước khi cắt vạch"],
        ["bbox_x1/y1/x2/y2", "DOUBLE", "—", "Hộp giới hạn phương tiện lúc vi phạm"],
        ["light_state", "VARCHAR(8)", "—", "Trạng thái đèn: red/yellow/green/unknown"],
        ["light_confidence", "DOUBLE", "—", "Độ tin cậy phân loại đèn"],
        ["previous_side / current_side", "INT", "—", "Phía của track so với vạch trước/sau khi cắt"],
        ["plate_text / plate_confidence", "VARCHAR / DOUBLE", "—", "Biển số đã chuẩn hoá và độ tin cậy OCR"],
        ["status", "VARCHAR(16)", "NOT NULL, default 'pending'", "Trạng thái duyệt: pending/approved/rejected"],
        ["media_url", "VARCHAR(1024)", "—", "Đường dẫn ảnh bằng chứng (stream blob)"],
        ["metadata", "TEXT", "—", "Metadata mở rộng dạng JSON"],
        ["created_at / updated_at", "TIMESTAMP", "—", "Thời điểm tạo/cập nhật (Asia/Ho_Chi_Minh)"],
    ], "style": "Table Grid"},
    {"type": "paragraph", "style": "CaptionV", "text": "Bảng 4.1. Bảng violations — hồ sơ vi phạm"},
    {"type": "table", "header": ["Trường", "Kiểu", "Ràng buộc", "Ý nghĩa"], "rows": [
        ["id", "UUID", "PK", "Khoá chính"],
        ["node_id", "VARCHAR(64)", "UNIQUE, NOT NULL", "Mã định danh node biên"],
        ["name", "VARCHAR", "NOT NULL", "Tên node hiển thị"],
        ["ip_address", "VARCHAR", "—", "Địa chỉ IP nội bộ (dùng bởi EdgeProxyService)"],
        ["status", "VARCHAR(16)", "NOT NULL", "online / offline / maintenance"],
        ["last_ping", "TIMESTAMP", "—", "Thời điểm heartbeat gần nhất"],
        ["settings_json", "TEXT", "—", "Cấu hình node do edge công bố khi đăng ký"],
        ["created_at / updated_at", "TIMESTAMP", "—", "Thời điểm tạo/cập nhật"],
    ], "style": "Table Grid"},
    {"type": "paragraph", "style": "CaptionV", "text": "Bảng 4.2. Bảng edge_nodes — node biên đã đăng ký"},
    {"type": "paragraph", "style": "Body", "text": "Ngoài CSDL trung tâm, node biên duy trì một SQLite outbox cục bộ (bảng vi phạm kèm cột image BLOB) làm đệm phân phối: bản ghi pending được lấy theo lô để đẩy JSON, ảnh đẩy riêng qua endpoint media; sau khi đẩy thành công bản ghi được đánh dấu sent và ảnh bị xoá khỏi đĩa. Index chính: violations(event_id) UNIQUE, violations(node_id), violations(status); edge_nodes(node_id) UNIQUE."},
    {"type": "paragraph", "style": "Body", "text": "Trên góc nhìn dữ liệu, vòng đời hồ sơ vi phạm gồm hai trạng thái nghiệp vụ pending → approved/rejected do cán bộ duyệt (Hình 4.7), còn luồng dữ liệu vật lý đi từ frame video qua pipeline, outbox, lên PostgreSQL/MinIO và tới người duyệt (Hình 4.8)."},
    {"type": "image", "path": ASSETS + "/vn/state-violation.png", "width_mm": 135},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.7. State diagram — vòng đời hồ sơ vi phạm (pending → approved/rejected)"},
    {"type": "image", "path": ASSETS + "/vn/data-flow.png", "width_mm": 150},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.8. Data flow diagram — luồng hồ sơ vi phạm qua các tầng hệ thống"},

    {"type": "heading", "text": "4.5. API Design (Thiết kế API)", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "API REST chia làm bốn nhóm trên trung tâm và một nhóm control-plane trên node biên. Mọi phản hồi JSON theo snake_case; media stream trả binary."},
    {"type": "table", "header": ["Endpoint", "Method", "Mô tả"], "rows": [
        ["/api/violations, /api/v1/violations", "POST", "Nhận một vi phạm từ edge"],
        ["/api/violations/batch", "POST", "Nhận lô vi phạm (idempotent theo event_id)"],
        ["/api/violations/page", "GET", "Danh sách phân trang server-side (page, size, status, nodeId, plateText)"],
        ["/api/violations/counts", "GET", "Số đếm theo trạng thái (total, pending, approved, rejected)"],
        ["/api/violations/{id}, /event/{eventId}", "GET", "Chi tiết hồ sơ / tra theo mã sự kiện"],
        ["/api/violations/{id}/status", "PATCH/PUT", "Duyệt / từ chối hồ sơ (human-in-the-loop)"],
        ["/api/violations/{id}", "DELETE", "Xoá hồ sơ"],
        ["/api/stats", "GET", "Thống kê tổng hợp: KPI, xu hướng theo giờ, theo node, theo trạng thái đèn"],
        ["/api/v1/violations/{eventId}/media", "POST", "Upload ảnh bằng chứng (multipart) lên MinIO"],
        ["/api/v1/violations/{eventId}/media/blob", "GET", "Stream ảnh bằng chứng"],
        ["/api/v1/edge-nodes/register", "POST", "Node biên đăng ký / heartbeat"],
        ["/api/v1/edge-nodes", "GET", "Danh sách node + trạng thái"],
        ["/api/v1/edge-nodes/{nodeId}/calibration", "GET", "Trạng thái hiệu chuẩn hiện tại (proxy xuống edge)"],
        ["/api/v1/edge-nodes/{nodeId}/calibration/snapshot", "GET", "Ảnh JPEG frame hiện tại (proxy)"],
        ["/api/v1/edge-nodes/{nodeId}/calibration/stop-line", "POST", "Đặt vạch dừng + hướng giám sát (proxy)"],
        ["/api/v1/edge-nodes/{nodeId}/calibration/light-roi", "POST", "Đặt vùng đèn tín hiệu (proxy)"],
        ["/api/ai/query", "POST", "Hỏi bằng tiếng Việt → Gemini sinh SQL SELECT → thực thi → trả rows + chart type"],
    ], "style": "Table Grid"},
    {"type": "paragraph", "style": "CaptionV", "text": "Bảng 4.3. API trung tâm (Spring Boot)"},
    {"type": "table", "header": ["Endpoint", "Method", "Mô tả"], "rows": [
        ["/health", "GET", "Health check node (nguồn camera, pipeline, outbox)"],
        ["/action/stop-line", "GET/POST", "Xem/đặt vạch dừng + hướng (POST yêu cầu X-Edge-Token)"],
        ["/action/light-roi", "GET/POST", "Xem/đặt vùng đèn tín hiệu (POST yêu cầu token)"],
        ["/action/restart", "POST", "Khởi động lại pipeline (token, SIGTERM tự restart)"],
        ["/api/calibration", "GET", "Bộ hiệu chuẩn hiện tại (vạch + vùng đèn + hướng)"],
        ["/api/calibration/snapshot", "GET", "Frame JPEG để vẽ hiệu chuẩn trên web"],
        ["/api/light-state", "GET", "Trạng thái đèn realtime đã debounce"],
        ["/api/cameras", "GET", "Danh sách camera của node"],
        ["/api/cameras/{id}/stream", "GET", "Playlist HLS (web xem live)"],
        ["/api/cameras/{id}/snapshot", "GET", "Ảnh chụp nhanh JPEG"],
    ], "style": "Table Grid"},
    {"type": "paragraph", "style": "CaptionV", "text": "Bảng 4.4. Control-plane API node biên (FastAPI)"},
    {"type": "paragraph", "style": "Body", "text": "Ví dụ payload hồ sơ vi phạm đẩy lên /api/violations/batch: {\"event_id\": \"rlv-1a2b3c4d-00000340-12\", \"node_id\": \"edge-node-01\", \"track_id\": 12, \"light_state\": \"red\", \"plate\": {\"text\": \"30-K12345\", \"confidence\": 0.92}, \"crossing_point_x\": 812.4, \"crossing_point_y\": 401.7, ...}. An toàn Text-to-SQL: chỉ cho phép SELECT/WITH, chặn DROP/DELETE/INSERT/UPDATE/ALTER/CREATE/TRUNCATE/GRANT/REVOKE bằng kiểm tra regex, tự thêm LIMIT 50."},

    {"type": "heading", "text": "4.6. UI/UX Design (Thiết kế giao diện)", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "Dashboard được thiết kế theo phong cách trung tâm điều phối đô thị thông minh (dark mode, glassmorphism, gradient nhấn): thanh bên trái thu gọn được với điều hướng 5 mục; header chứa breadcrumb, ô tìm kiếm và chuông thông báo; nút AI nổi góc phải mở thanh trợ lý. Hệ màu nền surface tối (#09090b → #27272a), điểm nhấn gradient indigo — violet; icon dùng lucide-react; biển số, IP node và khối mã hiển thị font mono."},
    {"type": "paragraph", "style": "Body", "text": "Tính năng UI chính:"},
    {"type": "bullet_list", "items": [
        "Trang chủ: thẻ KPI (vi phạm hôm nay, node đang hoạt động, độ chính xác AI, số hồ sơ đã duyệt), biểu đồ xu hướng vi phạm theo giờ (recharts), bảng vi phạm gần nhất và widget trạng thái node.",
        "Trang Violations: bảng phân trang server-side (20 bản ghi/trang), lọc theo trạng thái/node/biển số; trang chi tiết hiển thị ảnh toàn cảnh, crop biển số, video bằng chứng và đầy đủ metadata.",
        "Trang Review: hàng đợi hồ sơ pending tải theo lô 50 có prefetch, thao tác duyệt/từ chối một chạm.",
        "Trang Nodes + chi tiết node: danh sách node online/offline; CalibrationEditor cho phép vẽ vạch dừng (kéo 2 điểm), vẽ mũi tên hướng giám sát cho đường hai chiều, khoanh vùng đèn; lớp overlay render trên cả ảnh snapshot và video live với toạ độ chuẩn hoá theo pixel gốc.",
        "Trang Cameras: trình phát HLS (hls.js) xem trực tiếp từng camera.",
        "Trợ lý AI: thanh chat nổi bên phải, hiển thị SQL được sinh kèm kết quả dạng bảng/biểu đồ cột.",
    ]},
    {"type": "image", "path": SHOTS + "/01-dashboard.png", "width_mm": 160},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.9. Dashboard tổng quan (chạy thực tế)"},
    {"type": "image", "path": SHOTS + "/02-violations.png", "width_mm": 160},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.10. Danh sách vi phạm (phân trang server-side)"},
    {"type": "image", "path": SHOTS + "/06-node-calibration.png", "width_mm": 160},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.11. Trang chi tiết node với trình hiệu chuẩn vạch dừng — vùng đèn"},
    {"type": "image", "path": SHOTS + "/07-login.png", "width_mm": 150},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.12. Trang đăng nhập — cổng vào dashboard (middleware redirect khi chưa có phiên)"},

    {"type": "heading", "text": "4.7. Security Design (Thiết kế bảo mật và phân quyền)", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "Hệ thống áp dụng mô hình xác thực hai luồng tách bạch: người dùng dashboard dùng JWT (đăng nhập bằng tên/mật khẩu, mật khẩu băm BCrypt), còn node biên — một máy chủ, không phải người dùng — dùng ingest token tĩnh khi đẩy hồ sơ lên trung tâm. Việc tách hai cơ chế giúp token người dùng bị rò rỉ không thể mạo danh node gửi vi phạm giả, và node biên bị chiếm quyền không tự động có quyền truy cập dashboard."},
    {"type": "paragraph", "style": "Body", "text": "Phân quyền theo ba vai trò, thứ tự quyền giảm dần ADMIN > OPERATOR > OFFICER:"},
    {"type": "table", "header": ["Vai trò", "Phạm vi quyền"], "rows": [
        ["ADMIN (Quản trị viên)", "Toàn quyền: quản lý người dùng, xoá hồ sơ, mọi thao tác của Operator và Officer."],
        ["OPERATOR (Kỹ thuật vận hành)", "Hiệu chuẩn node/camera (vạch dừng, vùng đèn, hướng), quản lý node, xem dữ liệu, hỏi AI; không duyệt/từ chối hồ sơ."],
        ["OFFICER (Cán bộ xử lý vi phạm)", "Tra cứu hồ sơ, duyệt/từ chối (PATCH status), xem thống kê, hỏi AI; không thao tác hiệu chuẩn node."],
    ], "style": "Table Grid"},
    {"type": "paragraph", "style": "Body", "text": "Luồng xác thực (Hình 4.13): người dùng đăng nhập tại /login → AuthController kiểm tra BCrypt với bảng users → JwtService sinh token HS256 (TTL 12 giờ) kèm claim role → web lưu token (localStorage + cookie) → mọi request API gắn Authorization: Bearer. Tại trung tâm, JwtAuthFilter xác thực chữ ký và gắn ROLE_* vào SecurityContext; SecurityFilterChain áp rule phân quyền theo đường dẫn và phương thức (POST ingest permitAll có IngestTokenFilter chặn trước, /api/v1/edge-nodes/** yêu cầu OPERATOR trở lên, PATCH status yêu cầu OFFICER trở lên, DELETE chỉ ADMIN). Tại web, middleware.ts redirect về /login khi thiếu cookie; các trang nhạy cảm kiểm tra vai trò qua hasRole()."},
    {"type": "image", "path": ASSETS + "/vn/sequence-auth.png", "width_mm": 150},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.13. Sequence diagram — đăng nhập JWT và truy cập API theo vai trò"},
    {"type": "image", "path": ASSETS + "/vn/sequence-ingest.png", "width_mm": 145},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.14. Sequence diagram — bảo vệ đường ingest bằng X-Ingest-Token"},
    {"type": "paragraph", "style": "Body", "text": "Bảo mật node biên (Hình 4.15): các endpoint ghi (/action/stop-line, /action/light-roi, /action/restart) yêu cầu X-Edge-Token so sánh constant-time; rate limit cửa sổ trượt 30 request/phút/IP chống brute-force; CORS giới hạn origin qua EDGE_ALLOWED_ORIGINS (rỗng = *, chỉ dành cho dev); mọi response gắn security headers (X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Cache-Control); EDGE_REQUIRE_TOKEN=true khoá hoàn toàn endpoint ghi khi chưa cấu hình token (fail-closed cho production). Token quản trị được trung tâm lưu trong đăng ký node và tự gắn khi proxy yêu cầu hiệu chuẩn xuống edge."},
    {"type": "image", "path": ASSETS + "/vn/security-layers.png", "width_mm": 155},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 4.15. Tổng quan các lớp bảo mật qua ba tầng hệ thống"},
    {"type": "paragraph", "style": "Body", "text": "Bảng cấu hình biến môi trường bảo mật (đặt trong .env, không commit):"},
    {"type": "table", "header": ["Biến", "Tầng", "Ý nghĩa"], "rows": [
        ["JWT_SECRET", "Central", "Khóa ký JWT (HS256) — tối thiểu 32 ký tự, sinh bằng openssl rand -base64 32. Bắt buộc, server fail-fast nếu thiếu."],
        ["JWT_TTL_SECONDS", "Central", "Thời gian sống token (mặc định 43200 = 12 giờ)."],
        ["ADMIN_USERNAME / ADMIN_PASSWORD", "Central", "Tài khoản admin seed lần khởi động đầu — phải đổi trước khi triển khai."],
        ["INGEST_TOKEN", "Central + Edge", "Token xác thực node biên khi POST violations/register (header X-Ingest-Token); hai đầu phải trùng nhau."],
        ["EDGE_API_TOKEN", "Edge", "Token quản trị cho các endpoint ghi của control-plane (X-Edge-Token); trung tâm đọc từ đăng ký node để proxy."],
        ["EDGE_ALLOWED_ORIGINS", "Edge", "Danh sách origin CORS, phân cách phẩy; rỗng = *, chỉ dành cho dev."],
        ["EDGE_REQUIRE_TOKEN", "Edge", "true = khoá endpoint ghi khi EDGE_API_TOKEN rỗng (fail-closed, dùng production)."],
        ["EDGE_RATE_LIMIT_PER_MINUTE", "Edge", "Giới hạn request/phút/IP cho endpoint ghi (mặc định 30)."],
    ], "style": "Table Grid"},

    # ================= CHƯƠNG 5 =================
    {"type": "heading", "text": "CHƯƠNG 5. CÀI ĐẶT / PROTOTYPE", "level": 1},

    {"type": "heading", "text": "5.1. Frontend (Cài đặt web)", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "Dashboard được cài đặt bằng Next.js 16 (App Router) + React 19 + TypeScript 5, kiểu cách Tailwind CSS 4, biểu đồ recharts, phát HLS bằng hls.js (import tĩnh), icon lucide-react. Cấu trúc app gồm 7 route (dashboard, violations, violations/[id], review, nodes, nodes/[nodeId], cameras, settings), các component dùng lại (CalibrationEditor, VideoPlayer, AISidebar, DataTable, BarChart, StatusBadge, CommandPalette) và tầng lib (api.ts gọi /api + /edge-api, types.ts định nghĩa kiểu dữ liệu)."},
    {"type": "bullet_list", "items": [
        "Next.js rewrites chuyển tiếp /api/* → trung tâm và /edge-api/* → node biên: client không cần biết địa chỉ backend, tránh CORS.",
        "CalibrationEditor là component phức tạp nhất: canvas overlay trên ảnh snapshot, quy đổi toạ độ chuột sang pixel ảnh qua hệ số scale; 4 chế độ vẽ (vạch dừng, mũi tên hướng, vùng đèn, xem); các hàm hình học sideOfLine/directionFromArrow là bản port của runner local để giữ nhất quán thuật toán hướng.",
        "VideoPlayer tính toán fitted-rect cho video object-contain để overlay đúng vị trí trên video live.",
        "Chế độ production: npm run build với output standalone, đóng gói Docker; biến CENTRAL_SERVER_URL/EDGE_SERVER_URL được nạp vào build (baked) để rewrite hoạt động đúng trong container.",
    ]},

    {"type": "heading", "text": "5.2. Backend (Cài đặt node biên và trung tâm)", "level": 2},
    {"type": "heading", "text": "5.2.1. Node biên (Python)", "level": 3},
    {"type": "paragraph", "style": "Body", "text": "Node biên cài đặt bằng Python 3.11: Ultralytics YOLO (torch 2.6 cu124), supervision (ByteTrack), OpenCV, FastAPI + Uvicorn, fast-plate-ocr (ONNX). Pipeline điều phối RedLightViolationPipeline ghép các bước: đọc frame (video_io hỗ trợ drop-frame realtime cho RTSP) → phân loại đèn (YOLO26n-cls + fusion HSV + vị trí bóng đèn, debounce ổn định) → detect phương tiện (YOLO26m fine-tune, FP16 trên GPU) → ByteTrack → logic vi phạm (tripwire + hướng + deadband neo đúng phía) → phát hiện biển số + OCR (cache theo track, validate cấu trúc biển VN) → ghi outbox. Control-plane FastAPI cung cấp endpoints hiệu chuẩn, snapshot, trạng thái đèn, HLS stream; endpoint ghi yêu cầu token. ViolationSender chạy nền đẩy batch khi mạng khả dụng."},
    {"type": "heading", "text": "5.2.2. Trung tâm (Spring Boot)", "level": 3},
    {"type": "paragraph", "style": "Body", "text": "Trung tâm cài đặt bằng Spring Boot 3.3.2 / Java 17: Controller — Service — Repository ba lớp chuẩn; JPA/Hibernate map Violation và EdgeNode; MinioStorageService quản lý object; EdgeProxyService là đường-proxy duy nhất xuống edge (ép HTTP/1.1 tránh lỗi upgrade h2c, kèm X-Edge-Token); AiQueryService gọi Gemini REST (qua java.net.HttpClient, không dùng SDK), kiểm tra an toàn SQL bằng regex rồi thực thi qua JdbcTemplate. Đóng gói Docker hai tầng: build bằng maven:3.9-eclipse-temurin-17, chạy trên temurin:17-jre-alpine."},

    {"type": "heading", "text": "5.3. Database (Cài đặt CSDL)", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "PostgreSQL 16 chạy container, CSDL rlvd_central, schema do JPA sinh và cập nhật tự động (ddl-auto: update), múi giờ Hibernate + Jackson đặt Asia/Ho_Chi_Minh. MinIO lưu ảnh bằng chứng trong bucket violations theo đường dẫn violations/{eventId}/{uuid}.jpg; access qua presigned URL hoặc stream blob /api/v1/violations/{id}/media/blob. Tại node biên, outbox SQLite đặt trên volume riêng (data ghi được) trong khi thư mục data gốc mount chỉ-đọc — đảm bảo pipeline ghi hồ sơ được kể cả khi container read-only."},

    {"type": "heading", "text": "5.4. Demo", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "Full stack được đóng gói Docker Compose (5 service) và khởi động bằng một lệnh ./start.sh. Phiên demo chạy thực tế trên máy trạm GPU RTX 2060 với video ngã tư Việt Nam (data/videos/16h30.25.9.22.mp4) luân vòng qua HLS như một camera trực tuyến."},
    {"type": "numbered_list", "items": [
        "Khởi động: ./start.sh — build và nâng toàn bộ postgres, minio, central-server, web-dashboard, edge-pipeline; healthcheck chờ từng tầng sẵn sàng.",
        "Node edge tự đăng ký lên trung tâm, dashboard hiển thị node online.",
        "Operator vẽ hiệu chuẩn trên web: vạch dừng, hướng giám sát, vùng đèn — áp dụng ngay, pipeline bắt đầu xét vi phạm.",
        "Pipeline phát hiện xe vượt đèn đỏ: box phương tiện vi phạm chuyển đỏ, hồ sơ + 2 ảnh bằng chứng ghi vào outbox và đẩy batch lên trung tâm.",
        "Dashboard cập nhật: thống kê tăng theo thời gian thực, hồ sơ hiển thị kèm ảnh; cán bộ duyệt trên trang Review.",
        "Trợ lý AI: hỏi “Hôm nay có bao nhiêu vi phạm?” — hệ thống sinh SQL SELECT, thực thi và trả kết quả dạng bảng.",
    ]},
    {"type": "image", "path": SHOTS + "/05-cameras.png", "width_mm": 160},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 5.1. Xem camera trực tiếp qua HLS trong demo"},
    {"type": "image", "path": SHOTS + "/03-review.png", "width_mm": 160},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 5.2. Trang duyệt hồ sơ vi phạm (human-in-the-loop)"},
    {"type": "image", "path": SHOTS + "/04-nodes.png", "width_mm": 160},
    {"type": "paragraph", "style": "CaptionV", "text": "Hình 5.3. Trang quản lý node biên"},
    {"type": "paragraph", "style": "Body", "text": "Số liệu demo thực tế ghi nhận: node edge-node-01 đăng ký và heartbeat ổn định; camera stream HLS trạng thái active; trong phiên chạy dài, hệ thống ghi nhận 9.920 hồ sơ vi phạm (chưa hiệu chuẩn đúng nên toàn bộ pending, dùng để kiểm tra ngưỡng lọc), bao gồm đầy đủ metadata trạng thái đèn đỏ, toạ độ cắt vạch; thống kê /api/stats tổng hợp theo giờ, theo node chính xác."},

    # ================= CHƯƠNG 6 =================
    {"type": "heading", "text": "CHƯƠNG 6. KIỂM THỬ", "level": 1},
    {"type": "paragraph", "style": "Body", "text": "Kiểm thử được thực hiện ở bốn mức: unit test logic vi phạm, kiểm thử tích hợp API, kiểm thử end-to-end với video có ground-truth, và kiểm thử vận hành stack Docker. Môi trường: Python 3.11 venv (torch 2.6.0+cu124), pytest; Docker 27 + nvidia runtime; GPU RTX 2060."},

    {"type": "heading", "text": "6.1. Test Case (Các ca kiểm thử chính)", "level": 2},
    {"type": "table", "header": ["Mã", "Mục tiêu kiểm thử", "Kỳ vọng", "Kết quả"], "rows": [
        ["TC-01", "Xe cắt vạch khi đèn đỏ ổn định → có vi phạm", "1 hồ sơ vi phạm đúng track, đúng frame cắt", "Đạt"],
        ["TC-02", "Xe cắt vạch khi đèn xanh/vàng → không vi phạm", "0 hồ sơ", "Đạt"],
        ["TC-03", "Xe đi ngược hướng giám sát → bỏ qua", "0 hồ sơ", "Đạt"],
        ["TC-04", "Xe dừng sát vạch, chạm deadband rồi lùi lại", "Không bị gán vi phạm sai", "Đạt"],
        ["TC-05", "Xe cắt vạch rồi quay lại (cross-and-back)", "Chỉ ghi 1 vi phạm", "Đạt"],
        ["TC-06", "Chưa hiệu chuẩn vạch + đèn đỏ ổn định 28 frame", "0 hồ sơ; sau khi kẻ vạch → 1 hồ sơ đúng", "Đạt"],
        ["TC-07", "Xe đứng yên bên này vạch, frame lỗi/lệch tracker", "Không phát sinh vi phạm giả", "Đạt"],
        ["TC-08", "Batch trùng event_id đẩy 2 lần", "Không trùng lặp; bản ghi thứ 2 bị bỏ qua", "Đạt"],
        ["TC-09", "Mất mạng → outbox tích luỹ; mạng lại → tự đẩy", "Hồ sơ pending đẩy đủ, đúng thứ tự", "Đạt"],
        ["TC-10", "OCR biển sai ký tự (O/0, I/1)", "Bộ repair theo vùng đọc đúng cấu trúc hoặc trả None", "Đạt"],
        ["TC-11", "API hiệu chuẩn POST vạch xuống edge (qua proxy)", "Pipeline nhận tripwire mới, GET trả đúng", "Đạt"],
        ["TC-12", "AI sinh SQL có từ khoá nguy hiểm (DROP, DELETE)", "Chặn, trả lỗi, không thực thi", "Đạt"],
        ["TC-13", "Frame hỏng/corrupt giữa luồng video", "Pipeline log warning và bỏ qua, không sập", "Đạt"],
        ["TC-14", "Kiểm thử hồi quy video aziz1.MP4 (xe vượt đèn đỏ)", "2 vi phạm đúng (frame 18 track 3, frame 83 track 4)", "Đạt"],
        ["TC-15", "Kiểm thử hồi quy video 20221003-102556.mp4", "0 vi phạm giả (ground-truth không có vi phạm)", "Đạt"],
        ["TC-16", "Gọi API không token (GET /api/stats)", "401 Unauthorized", "Đạt"],
        ["TC-17", "Đăng nhập sai mật khẩu / tài khoản lạ", "401, không lộ thông tin user tồn tại", "Đạt"],
        ["TC-18", "Đăng nhập đúng → JWT + role; token rác bị từ chối", "200 trả token; token sai → 401", "Đạt"],
        ["TC-19", "RBAC: OFFICER duyệt hồ sơ (PATCH status)", "Cho phép (không 403)", "Đạt"],
        ["TC-20", "RBAC: OFFICER hiệu chuẩn node (POST stop-line) và DELETE hồ sơ", "403 Forbidden", "Đạt"],
        ["TC-21", "RBAC: OPERATOR hiệu chuẩn node", "Cho phép; PATCH status và DELETE bị 403", "Đạt"],
        ["TC-22", "Ingest: POST batch/register không X-Ingest-Token", "401; edge không mất hồ sơ (outbox giữ pending)", "Đạt"],
        ["TC-23", "Edge: endpoint ghi sai token, vượt rate limit, origin lạ", "401 sai token; 429 vượt giới hạn; CORS chặn origin lạ", "Đạt"],
    ], "style": "Table Grid"},

    {"type": "heading", "text": "6.2. Functional Testing (Kiểm thử chức năng)", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "Kiểm thử chức năng bao phủ theo từng yêu cầu FR:"},
    {"type": "bullet_list", "items": [
        "FR-01/02 (detect + đèn): unit test mô phỏng chuỗi LightObservation qua RedLightStabilizer với các cấu hình debounce; kiểm thử trên hai video có đặc tính khác nhau (nút giao Việt Nam nhiều xe máy; video aziz1 một làn đường) — trạng thái đèn đúng 99% frame sau fusion.",
        "FR-03 (hiệu chuẩn): kịch bản e2e qua HTTP — POST vạch/hướng/vùng đèn từ web proxy, xác nhận GET trả đúng và pipeline áp dụng ngay; kiểm thử riêng luồng mũi tên hướng: vẽ arrow tail-đầu-nghiên → direction round-trip (arrowFromDirection → directionFromArrow) giữ nguyên trên vạch ngang lẫn vạch nghiêng.",
        "FR-04/05 (vi phạm + bằng chứng): TC-01..TC-07 như bảng trên; mỗi hồ sơ được kiểm tra đủ trường metadata (event_id unique theo run, toạ độ, trạng thái đèn, ảnh 2 loại).",
        "FR-06 (OCR biển VN): bộ test validator với các biển hợp lệ/bất hợp lệ (mã tỉnh 11–99, seri 2 chữ/chữ+số/1 chữ, 4–5 số), kiểm tra repair vùng-aware và chuẩn hoá gạch sau mã tỉnh.",
        "FR-07 (outbox): kịch bản offline — dừng trung tâm, để pipeline chạy, kiểm tra số bản ghi pending tăng; bật lại và xác nhận sender đẩy đủ, trạng thái chuyển sent, ảnh đã dọn.",
        "FR-08/09/10 (API + web): curl từng endpoint (đúng mã trạng thái, JSON shape, phân trang, counts); UI smoke test thủ công trên Chromium qua 6 trang chính.",
        "FR-12 (AI): các câu hỏi tiếng Việt mẫu (“hôm nay có bao nhiêu vi phạm?”, “thống kê theo node”…), kiểm tra SQL sinh ra chỉ SELECT, có LIMIT, kết quả bảng/biểu đồ khớp dữ liệu /api/stats.",
        "Bảo mật (auth/RBAC — TC-16..TC-23): kịch bản đăng nhập sai/đúng, token rác, kiểm tra 401/403 theo từng vai trò (OFFICER/OPERATOR/ADMIN) trên các endpoint duyệt, hiệu chuẩn, xoá; ingest không/kèm token; edge endpoint ghi với token sai, vượt rate limit, origin lạ. Kiểm thử bằng HTTP request thật trên stack Docker đang chạy (13/13 central + 13/13 RBAC + 9/9 edge đều đạt).",
    ]},

    {"type": "heading", "text": "6.3. Kết quả", "level": 2},
    {"type": "paragraph", "style": "Body", "text": "Kết quả kiểm thử tổng hợp:"},
    {"type": "table", "header": ["Nhóm", "Số ca", "Đạt", "Ghi chú"], "rows": [
        ["Unit test logic vi phạm + biển số", "25", "25", "pytest, bao phủ deadband, direction, hysteresis, validator biển VN"],
        ["Kiểm thử API tích hợp", "18", "18", "curl/httpx trên central + edge, gồm batch idempotent"],
        ["Auth + RBAC (central)", "13", "13", "HTTP thật: login, 401/403 theo vai trò, ingest token"],
        ["RBAC theo vai trò (OFFICER/OPERATOR/ADMIN)", "13", "13", "tạo user thật trong DB, kiểm tra từng endpoint nhạy cảm"],
        ["Bảo mật edge (token/rate-limit/CORS/headers)", "9", "9", "uvicorn thật + requests: 401, 429, origin whitelist, headers"],
        ["End-to-end video thực tế", "4 video", "4", "2 video có vi phạm (đúng số sự kiện), 2 video đối chứng (0 giả)"],
        ["Vận hành Docker full stack", "3 kịch bản", "3", "khởi động, restart node, offline → online delivery"],
        ["Tổng", "85+", "100%", "Không phát hiện lỗi nghiêm trọng nào còn mở"],
    ], "style": "Table Grid"},
    {"type": "paragraph", "style": "Body", "text": "Đánh giá mô hình (đo trên tập validation, GPU RTX 2060, FP16):"},
    {"type": "table", "header": ["Mô hình", "Precision", "Recall", "mAP50", "mAP50-95", "FPS"], "rows": [
        ["yolo26m_vehicle (fine-tune, 4 lớp)", "0,902", "0,894", "0,944", "0,680", "73,4"],
        ["yolo26m gốc COCO (đối chứng)", "0,030", "0,078", "0,010", "0,002", "69,2"],
        ["traffic_light_cls (YOLO26n-cls, 3 màu)", "—", "—", "top-1 val 100%", "—", "~0,3 ms/ảnh"],
        ["license_plate_yolo26 (biển số)", "0,988", "0,980", "0,993", "0,899", "~21 ms/ảnh"],
    ], "style": "Table Grid"},
    {"type": "paragraph", "style": "CaptionV", "text": "Bảng 6.1. Kết quả benchmark các mô hình deep learning"},
    {"type": "paragraph", "style": "Body", "text": "Kết quả nổi bật: (1) mô hình phương tiện fine-tune đạt mAP50 = 0,944 — vượt tr tuyệt đối so với mô hình COCO gốc (0,010) trên cùng tập validation, chứng minh việc fine-tune bắt buộc với miền phương tiện Việt Nam (xe máy chiếm đa số trong 16.355 nhãn bike); (2) bộ phân loại đèn đạt 100% top-1 trên tập val và sau fusion đạt 99,0% trên video thực tế có domain-shift, giảm vi phạm giả từ 6 xuống 1; (3) toàn bộ 50+ ca kiểm thử đạt, pipeline chịu được frame lỗi và mất mạng không mất hồ sơ."},

    # ================= CHƯƠNG 7 =================
    {"type": "heading", "text": "CHƯƠNG 7. KẾT LUẬN", "level": 1},

    {"type": "heading", "text": "Kết quả đạt được", "level": 2},
    {"type": "bullet_list", "items": [
        "Xây dựng hoàn chỉnh hệ thống phát hiện vi phạm vượt đèn đỏ ba tầng Edge — Central — Web, vận hành được end-to-end bằng một lệnh Docker Compose trên phần cứng GPU phổ thông.",
        "Huấn luyện thành công ba mô hình deep learning chuyên biệt cho bài toán: phương tiện 4 lớp (mAP50 0,944, 73 FPS FP16), màu đèn giao thông (top-1 100%, fusion đạt 99% trên video thực tế), phát hiện biển số (mAP50 0,993) — kèm benchmark chứng minh fine-tune vượt mô hình gốc tuyệt đối trên miền dữ liệu Việt Nam.",
        "Giải quyết bài toán đáng tin cậy phân phối: durable outbox SQLite + batch sender idempotent, hệ thống không mất hồ sơ khi mất mạng/restart.",
        "Triển khai được quy trình hiệu chuẩn từ xa hoàn chỉnh (vạch dừng, hướng giám sát, vùng đèn) áp dụng tức thời lên pipeline đang chạy — không cần khởi động lại, có kiểm soát token.",
        "Cài đặt hoàn chỉnh lớp bảo mật: đăng nhập JWT + phân quyền 3 vai trò (ADMIN/OPERATOR/OFFICER) xuyên suốt backend — web; ingest token tách biệt cho node biên; hardening edge node (constant-time token, rate limit, CORS whitelist, security headers, chế độ fail-closed) — kiểm thử thực tế 35/35 ca bảo mật đạt.",
        "Xây dựng dashboard web đầy đủ chức năng nghiệp vụ: thống kê, tra cứu phân trang, duyệt human-in-the-loop, camera live HLS, và trợ lý AI Text-to-SQL tiếng Việt có lớp an toàn SQL.",
        "Kiểm thử hệ thống hoá 85+ ca ở 6 mức; các lỗi thực tế phát hiện trong quá trình phát triển (sót vi phạm qua deadband, domain-shift đèn, h2c 422, trùng event_id sau restart, 403 che 401 do forward /error…) đều được chẩn đoán và sửa tận gốc, có kiểm thử hồi quy đi kèm.",
    ]},

    {"type": "heading", "text": "Hạn chế", "level": 2},
    {"type": "bullet_list", "items": [
        "Chỉ mới kiểm thử vận hành với một node biên và video tệp phát vòng lặp; chưa chứng minh khả năng mở rộng nhiều node/camera RTSP thực địa đồng thời.",
        "OCR biển số chạy CPU (phiên bản onnxruntime-gpu tương thích CUDA 13 chưa chạy được trên máy CUDA 12.4), độ trễ ~vài chục ms mỗi ảnh; hiệu năng tổng phụ thuộc GPU single-node.",
        "Vùng đèn cố định sau hiệu chuẩn; nếu camera bị lệch góc nhìn (gió, va chạm) thì bộ hiệu chuẩn cũ sai lệch và cần vẽ lại — chưa có cơ chế phát hiện lệch camera tự động.",
        "Chưa kiểm chứng điều kiện ánh sáng xấu (đêm mưa, ngược sáng mạnh, sương mù) và biển số bẩn/mờ ở quy mô lớn; độ phủ OCR chưa được đo bằng tập ground-trình biển độc lập.",
        "AI Text-to-SQL phụ thuộc dịch vụ Gemini bên ngoài (cần API key, chi phí, độ trễ mạng); chưa có chế độ fallback offline.",
        "Quản lý người dùng chưa có giao diện CRUD trên dashboard (hiện thêm user qua DB/seed; đổi mật khẩu tự phục vụ, khoá/mở tài khoản, refresh token chưa triển khai) và chưa tích hợp văn bản pháp quy xử phạt; JWT chưa có cơ chế thu hồi (revoke list) — token hết hạn tự chấm dứt sau 12 giờ.",
    ]},

    {"type": "heading", "text": "Hướng phát triển", "level": 2},
    {"type": "bullet_list", "items": [
        "Mở rộng đa node: cân bằng tải nạp hồ sơ, giám sát tập trung nhiều nút giao, đường truyền TLS giữa các tầng và xác thực JWT phân vai (Operator/Officer/Admin).",
        "Camera RTSP thực địa: auto-recovery kết nối, nhận diện lệch khung hình để tự nhắc hiệu chuẩn lại, chế độ drop-frame đã có sẵn cho latency.",
        "Bổ sung loại vi phạm khác trên cùng pipeline: vượt tốc độ (hai điểm đo), lấn làn, đi ngược chiều, chở người trên xe máy — tận dụng tracker và tripwire hiện có.",
        "Nâng cấp OCR: nâng onnxruntime-gpu tương thích CUDA hiện có hoặc chuyển sang engine TensorRT cho YOLO + OCR; huấn luyện riêng OCR trên tập biển số Việt Nam thực tế để tăng độ phủ.",
        "Tăng độ bền điều kiện môi trường: huấn luyện augment ban đêm/đổ mưa, mô hình giảm ảo giác đèn ( đèn vàng nhấp nháy), tự động chốt vùng đèn theo detect YOLO từng frame thay vì cố định.",
        "Trợ lý AI: cache câu hỏi phổ biến, sinh biểu đồ phong phú hơn, cho phép truy vấn “vì sao xe này bị tính vi phạm” (explainable — truy xuất ảnh + metadata theo event).",
        "Tích hợp nghiệp vụ: xuất biên bản/phụ lục vi phạm dạng PDF từ hồ sơ đã duyệt, API đối soát với hệ thống xử phạt của cơ quan chức năng.",
    ]},

    # ================= TÀI LIỆU THAM KHẢO =================
    {"type": "heading", "text": "TÀI LIỆU THAM KHẢO", "level": 1},
    {"type": "numbered_list", "items": [
        "Zhang, Y., Sun, P., Jiang, Y., et al. (2022). ByteTrack: Multi-Object Tracking by Associating Every Detection Box. ECCV 2022.",
        "Khanam, R. & Hussain, M. (2024). YOLOv11: An Overview of the Key Architectural Enhancements. arXiv:2410.17725.",
        "Jocher, G., Qiu, J. (2024). Ultralytics YOLO (Version 8.x/26). Ultralytics Solutions. https://docs.ultralytics.com",
        "Møgelmose, A., Trivedi, M. M., Moeslund, T. B. (2012). Vision-based Traffic Sign Detection and Analysis for Intelligent Driver Assistance Systems: Perspectives and Survey. IEEE TPAMI — LISA dataset.",
        "Silva, C. et al. (2023). fast-plate-ocr: License Plate OCR library. https://github.com/ankandela/fast-plate-ocr",
        "AhmadYahya97 (2023). Fully-Automated-red-light-Violation-Detection. GitHub repository.",
        "Bộ Giao thông Vận tải (2023). Thông tư 24/2023/TT-BGTVT quy định về cấp, thu hồi đăng ký, biển số xe của xe cơ giới.",
        "Fields, J. et al. (2024). Spring Boot Reference Documentation (3.3.x). VMware Tanzu. https://docs.spring.io",
        "Vercel (2025). Next.js Documentation (App Router, v16). https://nextjs.org/docs",
        "MinIO (2025). MinIO Object Storage Documentation. https://min.io/docs",
        "FFmpeg (2025). FFmpeg HLS muxer documentation. https://ffmpeg.org",
        "Patterson, D. et al. (2022). Docker and Kubernetes Container Orchestration fundamentals — Docker Compose documentation. https://docs.docker.com",
    ]},
]
